modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = "https://github.com/UpperMoon0/Endless/issues"
license = "All Rights Reserved"

[[mods]]
modId = "endless"
version = "${version}"
displayName = "Endless"
authors = "NsTut"
description = '''
A Minecraft mod that removes or customizes the build height limits.
Allows building beyond vanilla height restrictions through simple configuration.
Configure minimum/maximum build heights or remove limits entirely.
'''
logoFile = "assets/endless/icon.png"

[[dependencies.endless]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endless]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endless]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
